### ISSUE TITLE
Would you consider creating a MLP-Mixer project like this?

### ISSUE THREAD

**Issue by jikerWRN** [lukemelas/PyTorch-Pretrained-ViT#17]
Hi, would you consider creating a MLP-Mixer project like this?
Thanks!

**Comment by lukemelas** [comment]
Hi, 

I was actually working on the same idea as MLP-Mixer when it came out. It's here: https://github.com/lukemelas/do-you-even-need-attention

Hope that helps!

**Comment by jikerWRN** [comment]
Ok, thanks!
